/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Payment {
  'id' : number,
  'screenshotMime' : string,
  'status' : PaymentStatus,
  'playerId' : number,
  'timestamp' : Time,
  'screenshotData' : Uint8Array,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Player {
  'id' : number,
  'status' : PlayerStatus,
  'contact' : string,
  'name' : string,
  'tournamentId' : TournamentId,
}
export type PlayerStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface Tournament {
  'id' : TournamentId,
  'date' : string,
  'slotsAvailable' : bigint,
  'name' : string,
  'slotsUsed' : bigint,
  'location' : string,
}
export type TournamentId = number;
export interface _SERVICE {
  'authenticateAdmin' : ActorMethod<[string, string], string>,
  'createTournament' : ActorMethod<
    [string, string, string, string, bigint],
    TournamentId
  >,
  'deleteTournament' : ActorMethod<[string, TournamentId], undefined>,
  'getPaymentPaymentCount' : ActorMethod<[], bigint>,
  'getPaymentsByPlayer' : ActorMethod<[number], Array<Payment>>,
  'getPlayersByTournament' : ActorMethod<[TournamentId], Array<Player>>,
  'getTournament' : ActorMethod<[TournamentId], [] | [Tournament]>,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'registerPlayer' : ActorMethod<[string, string, TournamentId], number>,
  'submitPayment' : ActorMethod<[number, Uint8Array, string], number>,
  'updatePaymentStatus' : ActorMethod<
    [string, number, PaymentStatus],
    undefined
  >,
  'updatePlayerStatus' : ActorMethod<[string, number, PlayerStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];