/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TournamentId = IDL.Nat32;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const Payment = IDL.Record({
  'id' : IDL.Nat32,
  'screenshotMime' : IDL.Text,
  'status' : PaymentStatus,
  'playerId' : IDL.Nat32,
  'timestamp' : Time,
  'screenshotData' : IDL.Vec(IDL.Nat8),
});
export const PlayerStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat32,
  'status' : PlayerStatus,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'tournamentId' : TournamentId,
});
export const Tournament = IDL.Record({
  'id' : TournamentId,
  'date' : IDL.Text,
  'slotsAvailable' : IDL.Nat,
  'name' : IDL.Text,
  'slotsUsed' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'authenticateAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createTournament' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [TournamentId],
      [],
    ),
  'deleteTournament' : IDL.Func([IDL.Text, TournamentId], [], []),
  'getPaymentPaymentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPaymentsByPlayer' : IDL.Func([IDL.Nat32], [IDL.Vec(Payment)], ['query']),
  'getPlayersByTournament' : IDL.Func(
      [TournamentId],
      [IDL.Vec(Player)],
      ['query'],
    ),
  'getTournament' : IDL.Func([TournamentId], [IDL.Opt(Tournament)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'registerPlayer' : IDL.Func(
      [IDL.Text, IDL.Text, TournamentId],
      [IDL.Nat32],
      [],
    ),
  'submitPayment' : IDL.Func(
      [IDL.Nat32, IDL.Vec(IDL.Nat8), IDL.Text],
      [IDL.Nat32],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Text, IDL.Nat32, PaymentStatus],
      [],
      [],
    ),
  'updatePlayerStatus' : IDL.Func([IDL.Text, IDL.Nat32, PlayerStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TournamentId = IDL.Nat32;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const Payment = IDL.Record({
    'id' : IDL.Nat32,
    'screenshotMime' : IDL.Text,
    'status' : PaymentStatus,
    'playerId' : IDL.Nat32,
    'timestamp' : Time,
    'screenshotData' : IDL.Vec(IDL.Nat8),
  });
  const PlayerStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat32,
    'status' : PlayerStatus,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'tournamentId' : TournamentId,
  });
  const Tournament = IDL.Record({
    'id' : TournamentId,
    'date' : IDL.Text,
    'slotsAvailable' : IDL.Nat,
    'name' : IDL.Text,
    'slotsUsed' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'authenticateAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [TournamentId],
        [],
      ),
    'deleteTournament' : IDL.Func([IDL.Text, TournamentId], [], []),
    'getPaymentPaymentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPaymentsByPlayer' : IDL.Func(
        [IDL.Nat32],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPlayersByTournament' : IDL.Func(
        [TournamentId],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'getTournament' : IDL.Func(
        [TournamentId],
        [IDL.Opt(Tournament)],
        ['query'],
      ),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'registerPlayer' : IDL.Func(
        [IDL.Text, IDL.Text, TournamentId],
        [IDL.Nat32],
        [],
      ),
    'submitPayment' : IDL.Func(
        [IDL.Nat32, IDL.Vec(IDL.Nat8), IDL.Text],
        [IDL.Nat32],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Text, IDL.Nat32, PaymentStatus],
        [],
        [],
      ),
    'updatePlayerStatus' : IDL.Func(
        [IDL.Text, IDL.Nat32, PlayerStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };