/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: number;
    status: PlayerStatus;
    contact: string;
    name: string;
    tournamentId: TournamentId;
}
export type Time = bigint;
export interface Tournament {
    id: TournamentId;
    date: string;
    slotsAvailable: bigint;
    name: string;
    slotsUsed: bigint;
    location: string;
}
export interface Payment {
    id: number;
    screenshotMime: string;
    status: PaymentStatus;
    playerId: number;
    timestamp: Time;
    screenshotData: Uint8Array;
}
export type TournamentId = number;
export enum PlayerStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    authenticateAdmin(email: string, password: string): Promise<string>;
    createTournament(token: string, name: string, date: string, location: string, slotsAvailable: bigint): Promise<TournamentId>;
    deleteTournament(token: string, id: TournamentId): Promise<void>;
    getPaymentPaymentCount(): Promise<bigint>;
    getPaymentsByPlayer(playerId: number): Promise<Array<Payment>>;
    getPlayersByTournament(tournamentId: TournamentId): Promise<Array<Player>>;
    getTournament(id: TournamentId): Promise<Tournament | null>;
    getTournaments(): Promise<Array<Tournament>>;
    registerPlayer(name: string, contact: string, tournamentId: TournamentId): Promise<number>;
    submitPayment(playerId: number, screenshotData: Uint8Array, screenshotMime: string): Promise<number>;
    updatePaymentStatus(token: string, paymentId: number, status: PaymentStatus): Promise<void>;
    updatePlayerStatus(token: string, playerId: number, status: PlayerStatus): Promise<void>;
}
import type { Payment as _Payment, PaymentStatus as _PaymentStatus, Player as _Player, PlayerStatus as _PlayerStatus, Time as _Time, Tournament as _Tournament, TournamentId as _TournamentId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async authenticateAdmin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateAdmin(arg0, arg1);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<TournamentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteTournament(arg0: string, arg1: TournamentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTournament(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTournament(arg0, arg1);
            return result;
        }
    }
    async getPaymentPaymentCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentPaymentCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentPaymentCount();
            return result;
        }
    }
    async getPaymentsByPlayer(arg0: number): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByPlayer(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByPlayer(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByTournament(arg0: TournamentId): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTournament(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTournament(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournament(arg0: TournamentId): Promise<Tournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournaments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournaments();
            return result;
        }
    }
    async registerPlayer(arg0: string, arg1: string, arg2: TournamentId): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPlayer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPlayer(arg0, arg1, arg2);
            return result;
        }
    }
    async submitPayment(arg0: number, arg1: Uint8Array, arg2: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: number, arg2: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, arg1, to_candid_PaymentStatus_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, arg1, to_candid_PaymentStatus_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updatePlayerStatus(arg0: string, arg1: number, arg2: PlayerStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerStatus(arg0, arg1, to_candid_PlayerStatus_n13(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerStatus(arg0, arg1, to_candid_PlayerStatus_n13(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_PaymentStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerStatus): PlayerStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tournament]): Tournament | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    screenshotMime: string;
    status: _PaymentStatus;
    playerId: number;
    timestamp: _Time;
    screenshotData: Uint8Array;
}): {
    id: number;
    screenshotMime: string;
    status: PaymentStatus;
    playerId: number;
    timestamp: Time;
    screenshotData: Uint8Array;
} {
    return {
        id: value.id,
        screenshotMime: value.screenshotMime,
        status: from_candid_PaymentStatus_n4(_uploadFile, _downloadFile, value.status),
        playerId: value.playerId,
        timestamp: value.timestamp,
        screenshotData: value.screenshotData
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    status: _PlayerStatus;
    contact: string;
    name: string;
    tournamentId: _TournamentId;
}): {
    id: number;
    status: PlayerStatus;
    contact: string;
    name: string;
    tournamentId: TournamentId;
} {
    return {
        id: value.id,
        status: from_candid_PlayerStatus_n9(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        name: value.name,
        tournamentId: value.tournamentId
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PlayerStatus {
    return "pending" in value ? PlayerStatus.pending : "approved" in value ? PlayerStatus.approved : "rejected" in value ? PlayerStatus.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n7(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerStatus): _PlayerStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == PlayerStatus.pending ? {
        pending: null
    } : value == PlayerStatus.approved ? {
        approved: null
    } : value == PlayerStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
